name: nsidc-cryosphere-glossary
channels:
 - conda-forge
 - default
dependencies:
 - python ~=3.12

 ###################################################
 # Imported dependencies and extensions            #
 ###################################################

 - jupyterlab
 - pytest
 - pyyaml
